%% Functional requirements
%%   - Search for events
%%   - View event details
%%   - Purchase tickets
%%   - View purchased tickets

%% Non-functional requirements
%%   - Many users should be able to search and purchase tickets simultaneously without performance degradation.
%%   - Millions of simultaneous users trying to purchase tickets for popular events should not cause the system to crash.

flowchart TD
    A[Christmas] -->|Get money| B(Go shopping)
    B --> C{Let me think}
    C -->|One| D[Laptop]
    C -->|Two| E[iPhone]
    C -->|Three| F[fa:fa-car Car]