%% Functional requirements
%%   - Search for events
%%   - View event details
%%   - Purchase tickets
%%   - View purchased tickets

%% Non-functional requirements
%%   - Many users should be able to search and purchase tickets simultaneously without performance degradation.
%%   - Millions of simultaneous users trying to purchase tickets for popular events should not cause the system to crash.
%%   - Tens of thousands of events

%% API
%% /search?q={query} - GET -  Search for events
%% /events/{event_id} - GET -  Get event details
%% /payment-method - POST -  create a payment method (POST request with payment token from stripe)
%% /purchase - POST -  Purchase tickets (POST request with event_id, quantity, and payment method id)

flowchart LR
  U[User] -->|Search for events| S[Search Service]
  S --> D@{ shape: database, label: "Database" }

