%% Functional requirements
%%   - Search for events
%%   - View event details
%%   - Purchase tickets
%%   - View purchased tickets

%% Non-functional requirements
%%   - Many users should be able to search and purchase tickets simultaneously without performance degradation.
%%   - Millions of simultaneous users trying to purchase tickets for popular events should not cause the system to crash.
%%   - Tens of thousands of events

%% Models
%% Event: id, name, date, venue, available_tickets
%% User: id, name, email
%% Ticket: id, event_id, user_id, purchase_date, payment_method_id

%% API
%% /search?q={query} - GET -  Search for events
%% /events/{event_id} - GET -  Get event details
%% /payment-method - POST -  create a payment method (POST request with payment token from stripe)
%% /purchase - POST -  Purchase tickets (POST request with event_id, quantity, and payment method id)
%% /tickets - GET -  View purchased tickets (GET request with user authentication)

flowchart LR
  U[User]
  St@{ shape: circle, label: "Stripe" }
  subgraph ticketmaster cloud
    S[Search Service]
    D@{ shape: database, label: "Database" }
    TP[Ticketing Purchase Service]
    R@{ shape: database, label: "Redis ⚡️" }
    Q@{ shape: horizontal-cylinder, label: "Queueing Service (Kafka)" }
  end
  U -->|Search/View events| S[Search Service]
  S -->|Get event details| D
  S -->|Get available seats| R
  U -->|Get in queue to purchase| Q
  Q -->|Get next batch of users| TP
  TP -->|"Notify they are next in line (polling/ws)"| U
  U -->|Create payment method| St
  U -->|Purchase tickets - payment token| TP
  TP -->|Process payment| St
  TP -->|Save ticket| D
  TP -->|Update available seats| R
